export const TermsOfUse = `Terms of Use

Last updated: 출시일자 , 2024
Article 1 (Purpose)
These General Terms of Use (“these Terms") govern access to or use of the applications, websites, content, products or services (the “Services”) made available by OKIVERY (the “Company”).
Please read these Terms carefully before accessing or using the Services.
Your access and use of the Services constitutes your agreement to be bound by these Terms, which establishes a contractual relationship between you and the Company. If you do not agree to these Terms, you must not access or use the Services. These Terms expressly supersede prior contracts or agreements with you regarding the use of the Services. In the event of any material breach of your obligations under these Terms or any violation of any laws relating to the Services, the Company may notify you in advance of any such breach within a certain period of time, and may terminate these Terms or the Services if you fail to comply without any justifiable reason. In addition, the Company may revise, modify or terminate all or part of the Services if there is a substantial need for the operation or improvement of the Services. Provided, however, that the Company shall notify you in advance of any material or adverse event to you of any revision, modification or termination of the Services.
Supplementary terms may apply to certain Services, such as for a particular event, activity, or promotion. Such supplementary terms regarding applicable Services will be notified to you. Supplementary terms are in addition to, and shall be deemed a part of, the Terms of the applicable Services. Supplementary terms shall prevail over these Terms in the event of a conflict with respect to the applicable Services.
The Company may amend these Terms, policies and supplementary terms for the Services from time to time. If the Company amends the terms, or policies or supplemental terms, related to the Services, the Company shall notify you, either through public posting or individual notice, of such changes seven (7) days prior to the effective date, stating the reason for such amendment and the effective date. In the event of any amendment of the Terms that is unfavorable to you, we will notify you individually 30 days prior to the effective date. If you do not express your intention to refuse the amended Terms by the effective date and the Company clearly states that the amended Terms shall be deemed to have agreed upon absent such refusal, you shall be deemed to have agreed to the amended Terms. If you do not agree to the amended Terms, the Company may not be able to provide Services subject to the amended Terms.
The Company’s collection and use of personal information in connection with the Services is as described in the Company's Privacy Notice located at https://www.okivery.com/legal. If there is any complaint, dispute or conflict relating to you or a third party provider (including a transportation network company driver), and such data or information is required to resolve such complaint, dispute or conflict, the Company may provide any required information (including your contact information) to a claim processor or an insurer.



Services
The Services constitute a technology platform that enables users of the Company’s mobile applications or websites provided as part of the Services (each, an "Application") to arrange or schedule transportation and/or logistics services with independent third party service providers (including independent third party transportation service providers and independent third party logistics service providers) pursuant to an agreement with the Company or any of its affiliates (the “Third Party Providers"). Unless otherwise agreed by the Company in a separate written agreement with you, the Services are made available solely for your personal, noncommercial use. You acknowledge that the Company does not provide transportation or logistics services or act as a transportation service provider and that all of these transportation or logistics services will be provided by independent third party contractors not employed by the Company or its affiliates.
License.
On the condition that you comply with these Terms, the Company grants you for no consideration a limited, non-exclusive, non-sub-licensable, revocable, non-transferable license to: (i) access and use the Applications on your personal device solely in connection with your use of the Services; and (ii) access and use any content, information and related materials that may be made available through the Services, in each case solely for your personal, noncommercial use. Any rights not expressly granted herein are reserved by the Company and the Company‘s licensors.
Restrictions.
You may not: (i) remove any copyright, trademark or other proprietary notices from any portion of the Services; (ii) reproduce, modify, prepare derivative works based upon the Services, or publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Services except as expressly permitted by the Company; (iii) decompile, reverse analyze or disassemble the Services except as may be permitted by applicable law; (iv) link to, mirror or frame any portion of the Services; (v) conduct any act of scraping, indexing, surveying, or otherwise data mining any portion of the Services, or unduly burdening or hindering the operation and/or functionality of any aspect of the Services; or (vi) attempt to gain unauthorized access to or impair any aspect of the Services or its related systems or networks.
Third Party Services and Content.
Any third party services and content (including advertising) that the Company does not control may be made available by the Services or accessed through the Services. You acknowledge that different terms of use and privacy policies may apply to your use of such third party services and content. The Company does not guarantee such third party services and content and the Company is not responsible or (legally) liable for any products or services of such Third Party Providers; provided, however, that this shall not apply in the case of intentional wrongdoing or negligence of the Company and, as to damages going beyond the ordinary scope owing to special circumstances, the Company shall be responsible according to the Civil Code and other relevant laws. Additionally, Apple Inc., Google, Inc., Microsoft Corporation or BlackBerry Limited and/or other applicable overseas subsidiaries and affiliates will be third-party beneficiaries to these Terms if you access the Services using Applications developed for Apple iOS, Android, Microsoft Windows, or Blackberry-powered mobile devices, respectively. These third party beneficiaries are not parties to this Agreement and are not responsible for the provision or support of the Services in any manner. Your access to the Services using these devices is subject to terms set forth in the applicable third party beneficiary's terms of service.
Ownership.
The Services and all rights therein are and shall remain the Company's property or the property of the Company's licensors. Neither these Terms nor your use of the Services convey or grant to you any rights: (i) in or related to the Services except for the limited license granted above; or (ii) to use or reference in any manner the Company's corporate names, logos, product and service names, trademarks or services marks or those of the Company's licensors.
Your Use of the Services
User Account.
In order to use most aspects of the Services, you must register for and maintain an active personal user Services account ("Account"). You must be at least 18 years of age to create an Account. Account registration requires you to submit to the Company certain personal information, such as your name, address, mobile phone number and age, as well as at least one valid payment method (credit card or approved payment partner). You agree to maintain accurate, complete, and up-to-date information in your Account. In case of your failure to maintain accurate, complete, and up-to-date Account information, including having an invalid or expired payment method on file, the Company may notify you in advance to request correction of inaccuracies in your account information within a certain period of time, and if you fail to respond without a justifiable reason, you may not be able to access and use the Services and the Company may terminate this Agreement with you. You are responsible for the activities that occur in your account, except in the case of intentional wrongdoing or negligence of the Company, and you agree to maintain the security and secrecy of your Account username and password at all times. Unless otherwise permitted by the Company in writing, you may only possess one Account.
User Requirements and Conduct.
The Services are not available for use by persons under the age of 18. You may not authorize third parties to use your Account, and you may not allow persons under the age of 18 to receive transportation or logistics services from Third Party Providers unless they are accompanied by you. You may not assign or otherwise transfer your Account to any other person or entity. You agree to comply with all applicable laws when accessing or using the Services, and you may only access or use the Services for lawful purposes (e.g., no transport of unlawful or hazardous materials). You may not in your access or use of the Services cause nuisance, annoyance, inconvenience, or property damage, whether to the Third Party Provider or any other party. In certain instances you may be asked to provide proof of identity to access or use the Services, and you agree that you may be denied access to or use of the Services if you refuse to provide proof of identity.
Text Message.
By creating an Account, you agree that the Services may send you text messages (SMS) as part of the normal business operation of your use of the Services. You may opt out of receiving text messages (SMS) from the Company at any time by sending an email stating your intent to refuse to receive text messages and the telephone number at which you receive text messages to support@ut.taxi. You acknowledge that if you do not receive text messages (SMS), your use of the Services may be affected thereby.
Promotional Code.
The Company may, in the Company's sole discretion, create promotional codes that may be redeemed for Account credit, or other features or benefits related to the Services and/or a Third Party Provider's services, subject to any additional terms that the Company establishes on a per promotional code basis ("Promo Codes"). You agree that Promo Codes: (i) must be used for the intended audience and purpose, and in a lawful manner; (ii) may not be duplicated, sold or transferred in any manner, or made available to the general public (whether posted to a public form or otherwise), unless expressly permitted by the Company; (iii) may be disabled by the Company at any time for any reason without liability to the Company; (iv) may only be used pursuant to the specific terms that the Company establishes for such Promo Code; (v) are not valid for cash; and (vi) may expire prior to your use. The Company reserves the right to withhold or deduct credits or other features or benefits obtained through the use of Promo Codes by you or any other user in the event that the Company determines or believes that the use or exchange of the Promo Code was in error, fraudulent, illegal, or in violation of the applicable Promo Code terms or these Terms.
Content Provided by User.
The Company may, in its sole discretion, permit you from time to time to submit, upload, publish or otherwise make available to the Company commentary and feedback related to the Services, initiation of support requests, and submission of entries for competitions and promotions, along with textual, audio, and/or visual content and information through the Services ("User Content"). Any User Content provided by you remains your property. However, by providing User Content to the Company, you grant the Company a worldwide, perpetual, irrevocable, transferable, royalty-free license, with the right to sublicense, to use, copy, modify, create derivative works of, distribute, publicly display, publicly perform, and otherwise exploit in any manner such User Content in all formats, editions, and distribution channels now known or hereafter devised (including in connection with the Services and the Company's business and on third party sites and services), without further notice to or consent from you, and without any obligation of payment to you or any other person or entity.
You represent and warrant that: (i) you either are the sole and exclusive owner of all User Content or you have all rights, licenses, consents and permissions necessary to grant the Company the license to the User Content as set forth above; and (ii) neither the User Content, nor your submission, uploading, publishing or otherwise making available of such User Content, nor the Company's use of the User Content as permitted herein will infringe, misappropriate or violate a third party's intellectual property or proprietary rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.
You agree to not provide User Content that is defamatory, libelous, hateful, violent, obscene, pornographic, unlawful, or otherwise offensive, as determined by the Company in its sole discretion, regardless of whether or not such material may be protected by law. The Company may, but shall not be obligated to, review, monitor, and remove User Content, at the Company's sole discretion and at any time and for any reason, without notice to you.
Network Access and Devices.
You are responsible for obtaining the data network access necessary to use the Services. Your mobile network's data and messaging rates and fees may apply if you access or use the Services from a wireless-enabled device and you shall be responsible for such rates and fees. You are responsible for acquiring and updating compatible hardware or devices necessary to access and use the Services and Applications and any updates thereto. The Company does not guarantee that the Services, or any portion thereof, will function on any particular hardware or devices. In addition, the Services may be subject to malfunctions and delays inherent in the use of the Internet and electronic communications.
Payment
You understand that use of the Services may result in charges to you for the services or goods you receive from Third Party Providers ("Charges"). After you have received services or goods obtained through your use of the Service, in principle, the Company will, as the Third Party Providers’ limited payment collection agent, facilitate your payment of the applicable Charges on behalf of the Third Party Providers. Payment of the Charges in such manner shall be considered the same as payment made directly by you to the Third Party Providers. Depending on the type of Services provided to you, you may also be permitted to pay the applicable Charges directly to the Third Party Provider in cash or credit card. Charges will include applicable taxes where required by law. Charges you pay are final and non-refundable, unless otherwise determined by the Company.
All Charges are due immediately and payment will be facilitated by the Company using the preferred payment method designated in your Account, after which the Company will send you a receipt by email. If your primary Account payment method is determined to be expired, invalid or otherwise not able to be charged, you agree that the Company may, as the Third Party Providers’ limited payment collection agent, use a secondary payment method in your Account, if available.
As between you and the Company, the Company reserves the right to, in its sole discretion, establish, remove and/or revise Charges for any or all services or goods obtained through the use of the Services at any time on behalf of the Third Party Providers. The Company will use reasonable efforts to inform you of Charges that may apply, provided that you will be responsible for Charges incurred under your Account regardless of your awareness of such Charges or the amounts thereof. The Company may from time to time provide certain users with promotional offers that may result in different amounts charged for the same or similar services or goods obtained through the use of the Services. However, you agree that such promotional offers, unless also made available to you, shall have no bearing on your use of the Services or the Charges applied to you. You may elect to cancel your request for services or goods from a Third Party Provider at any time prior to such Third Party Provider's arrival, in which case you may be charged a cancellation fee.
The above payment structure is intended to fully compensate the Third Party Provider for the services or goods it provided. Any representation by the Company (on the Company’s website, in the Application, or in the Company’s marketing materials) to the effect that tipping is "voluntary," "not required," and/or "included" in the payments you make for services or goods provided is not intended to suggest that the Company provides any additional amounts, beyond those described above, to the Third Party Provider. You understand and agree that, while you are free to provide additional payment as a gratuity to any Third Party Provider who provides you with services or goods obtained through the Service, you are under no obligation to do so. Gratuities are voluntary. After you have received services or goods obtained through the Service, you will have the opportunity to rate your experience and leave additional feedback about your Third Party Provider.
Repair or Cleaning Fees. 
You shall be responsible for the cost of repair for damage to, or necessary cleaning of, any vehicle or property of any Third Party Provider resulting from use of the Services under your Account in excess of normal "wear and tear" damages and necessary cleaning ("Repair or Cleaning"). In the event that the Third Party Provider reports the need for Repair or Cleaning, and such Repair or Cleaning request is verified, the Company reserves the right to facilitate payment for the reasonable cost of such Repair or Cleaning using your payment method designated in your Account on behalf of the Third Party Provider. Such amounts will be transferred by the Company to the relevant Third Party Provider and are non-refundable.
Disclaimers, Limitation of Liability and Indemnity
Disclaimer.
THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE." THE COMPANY DISCLAIMS ALL REPRESENTATIONS AND WARRANTIES, EXPRESS, IMPLIED, OR STATUTORY, NOT EXPRESSLY SET OUT IN THESE TERMS, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN ADDITION, THE COMPANY MAKES NO REPRESENTATION, WARRANTY, OR GUARANTEE REGARDING THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, OR AVAILABILITY OF THE SERVICES OR ANY SERVICES OR GOODS REQUESTED THROUGH THE USE OF THE SERVICES, OR THAT THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. THE COMPANY DOES NOT GUARANTEE THE QUALITY, SUITABILITY, SAFETY OR ABILITY OF THIRD PARTY PROVIDERS. OTHER THAN AS ARISING FROM INTENTIONAL WRONGDOING OR NEGLIGENCE OF THE COMPANY, YOU BEAR THE RISK OF LOSSES ARISING OUT OF YOUR USE OF THE SERVICES, AND ANY SERVICE OR GOOD REQUESTED IN CONNECTION THEREWITH; PROVIDED, HOWEVER, THAT AS TO DAMAGES GOING BEYOND THE ORDINARY SCOPE OWING TO SPECIAL CIRCUMSTANCES, THE COMPANY SHALL BE RESPONSIBLE ACCORDING TO THE CIVIL CODE AND OTHER RELEVANT LAWS.
Limitation of Liability.
THE COMPANY SHALL INDEMNIFY FOR ORDINARY DAMAGES ARISING FROM THE COMPANY’S INTENTIONAL WRONGDOING OR NEGLIGENCE IN CONNECTION WITH THE USE OF THE SERVICES, BUT OTHERWISE THE COMPANY SHALL NOT BE HELD LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR ANY OTHER DAMAGES, INCLUDING LOST PROFITS, LOST DATA, PERSONAL INJURY, OR PROPERTY DAMAGE RELATED TO, IN CONNECTION WITH, OR OTHERWISE RESULTING FROM ANY USE OF THE SERVICES. AS TO DAMAGES GOING BEYOND THE ORDINARY SCOPE OWING TO SPECIAL CIRCUMSTANCES, THE COMPANY SHALL BE RESPONSIBLE ACCORDING TO THE CIVIL CODE AND OTHER RELEVANT LAWS. THE COMPANY SHALL NOT BE HELD LIABLE FOR ANY DAMAGES, LIABILITY OR LOSSES ARISING OUT OF THE FOLLOWING, OTHER THAN LIABILITY FOR COMPENSATION OF ORDINARY DAMAGES ARISING FROM THE COMPANY’S INTENTIONAL WRONGDOING OR NEGLIGENCE, AND. AS TO DAMAGES GOING BEYOND THE ORDINARY SCOPE OWING TO SPECIAL CIRCUMSTANCES, SHALL BE RESPONSIBLE ACCORDING TO THE CIVIL CODE AND OTHER RELEVANT LAWS: (i) YOUR USE OF OR RELIANCE ON THE SERVICES OR YOUR INABILITY TO ACCESS OR USE THE SERVICES; OR (ii) ANY TRANSACTION OR RELATIONSHIP BETWEEN YOU AND ANY THIRD PARTY PROVIDER, EVEN IF THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE COMPANY SHALL NOT BE HELD LIABLE FOR DELAY OR FAILURE IN PERFORMANCE RESULTING FROM CAUSES BEYOND THE COMPANY’S REASONABLE CONTROL. THE COMPANY SHALL COMPENSATE FOR DAMAGES CAUSED BY THE COMPANY’S INTENTIONAL WRONGDOING OR NEGLIGENCE IN CONNECTION WITH THE USE OF THE SERVICES, BUT. AS TO DAMAGES GOING BEYOND THE ORDINARY SCOPE OWING TO SPECIAL CIRCUMSTANCES, SHALL BE RESPONSIBLE ACCORDING TO THE CIVIL CODE AND OTHER RELEVANT LAWS.
THE COMPANY’S SERVICES MAY BE USED BY YOU TO REQUEST AND SCHEDULE TRANSPORTATION, GOODS, OR LOGISTICS SERVICES WITH THIRD PARTY PROVIDERS, BUT YOU AGREE THAT THE COMPANY HAS NO RESPONSIBILITY OR LIABILITY FOR COMPENSATION TO YOU RELATED TO ANY TRANSPORTATION, GOODS, OR LOGISTICS SERVICES PROVIDED TO YOU BY THIRD PARTY PROVIDERS EXCEPT IN THE CASE OF INTENTIONAL WRONGDOING OR NEGLIGENCE OF THE COMPANY.
THE LIMITATIONS AND DISCLAIMER IN THIS SECTION 5 HEREOF DO NOT PURPORT TO LIMIT LIABILITY OR ALTER YOUR RIGHTS AS A CONSUMER THAT CANNOT BE EXCLUDED UNDER APPLICABLE LAW.
Indemnity.
You agree to indemnify and hold the Company and its officers, directors, employees, and agents harmless from any and all claims, demands, losses, indemnification liabilities, and expenses (including attorneys' fees), arising out of or in connection with: (i) your use of the Services or services or goods obtained through your use of the Services; (ii) your breach or violation of any of these Terms; (iii) the Company’s use of your User Content; or (iv) your violation of the rights of any third party, including Third Party Providers; provided, however, that in the event of a cause attributable to the Company, the scope of such indemnification, and holding harmless, shall be reduced according to the proportion attributable to Company.
Governing Law and Arbitration
Except as otherwise expressly provided herein, if any dispute arises between the Company and you in connection with the use of the Services, both parties shall consult with each other in good faith to resolve the dispute; provided, however, that if the dispute cannot be resolved, either party may file a lawsuit with the district court having jurisdiction over the address of the user at the time of filing of the lawsuit (or the district court having jurisdiction over the place of residence, if the user has no address at the time of filing of the lawsuit), except when the address or place of residence of the user filing a lawsuit is unknown. Any dispute between the Company and you arising out of or relating to the use of the Services shall be settled under the laws of the Republic of Korea.
Other Provisions
Claims of Copyright Infringement.
Claims of copyright infringement should be sent to the Company's designated agent. Please visit the Company's web page at https://www.okivery.com/legal for the designated address and additional information.
Notice.
The Company may give you notice by means of a general notice on the Services, electronic mail to your email address in your Account, or by regular mail to your address in your Account. You may give notice to the Company by mail in writing to the following address of the Company: 15/F, 343 Samil-daero, Jung-gu, Seoul, Korea.
General.
You may not assign these Terms in whole or in part without the Company’s prior written approval. You approve the Company to assign or transfer these Terms in whole or in part, including to: (i) a subsidiary or affiliate; (ii) an acquirer of the Company’s equity, business or assets; or (iii) a successor by merger. No joint venture, partnership, employment, or agency relationship exists between you and the Company or any Third Party Provider as a result of this Agreement between you and the Company or use of the Services.
If any provision of these Terms is held to be illegal, invalid or unenforceable, in whole or in part, under any law, such provision or part thereof shall to that extent be deemed not to form part of these Terms, but the legality, validity and enforceability of the other provisions in these Terms shall not be affected. In that event, the parties shall replace the illegal, invalid or unenforceable provision or part thereof with a provision or part thereof that is legal, valid and enforceable and that has, to the greatest extent possible, a similar effect as the illegal, invalid or unenforceable provision or part thereof, given the contents and purpose of these Terms. These Terms constitute the entire agreement and understanding of the parties with respect to the subject matter hereof and replace and supersede all prior or contemporaneous agreements or undertakings regarding such subject matter. In these Terms, the words “including” and “include” mean “including, but not limited to.”
Supplementary Terms for Korean Users
Article 1 Purpose
These Supplementary Terms for Korean Users (“These Terms") are intended to stipulate matters on the rights, obligations and responsibilities of UT LLC (the “Company”) and the user of the location-based service (“Service”) provided by the Company, who have agreed to these Terms (“User”)
Article 2 Application of Terms and Conditions
When User use location-based services (“Location-Based Services”), These Terms and Terms and Conditions as of April 1, 2021 (“Standard Terms and Conditions”) apply to User. In the event of a conflict between These Terms and Standard Terms and Conditions, These Terms shall prevail.
Article 3 Service Fee
Partner drivers (and passengers) can use the Company's Location-Based Services free of charge.
Article 4 Service content
The Company provides on-demand transportation and logistics services to drivers and passengers through a mobile application or website.
Article 5 Use and Provision of Personal Location Information
If the Company intends to provide Service by using personal location information, the Company will specify it in These Terms and obtain consent from the data subject in advance.
The Company uses only the minimum necessary personal location information to provide Location-Based Services. The purposes for which the Company uses personal location information are as follows:
Searching pick-up / drop-off locations and providing location points during trips, based on location
Searching the vicinity and providing route guidance, based on location
Providing the Company's personalized services and advertisement, based on location
The Company destroys the personal location information and the materials confirming the use and provision of location information that the Company is required by the Act on the Protection and Use of Location Information to record and retain if the Company uses User’s personal location information. This is done without delay upon User’s withdrawal from Service or once the purpose of the use has been achieved. However, if there is a legal obligation to retain the data, it will be preserved for the required period stipulated by relevant regulations.
The Company automatically records and preserves data confirming the use and provision of location information to settle charges and handle customer complaints with other businesses or customers, and the data is kept for one year.
The Company provides User's personal location information to a third party designated by User in order to provide membership taxi and electronic call-taxi services. In the case of providing personal location information to a third party, User is notified immediately of the recipient, the date and time of provision, and the purpose of provision each time through the communication device that collected the personal location information. However, if it falls under any of the following subparagraphs, it will be notified to the communication device or e-mail address designated in advance by User.
If the communication device that collected the personal location information does not have a function to receive text, voice or video
If User has requested in advance to be notified by means such as online posting
Article 6 Rights of subject of personal location information
User can withdraw all or part of the consent given to the Company for the provision of Location-Based Services using personal location information and the provision of personal location information to third parties at any time. In this case, the Company destroys the collected personal location information and data confirming the use and provision of location information
User can request the Company to temporarily suspend the collection, use, or provision of personal location information at any time, and the Company cannot refuse and has technical means in place to do so.
User may request the Company to view or notify the data in each of the following subparagraphs, and may request correction if there is an error in the data. In this case, the Company cannot refuse such a request without justifiable reasons.
Data confirming the use and provision of location information
The reason and contents of the personal location information provided to a third party in accordance with the Act on the Protection and Use of Location Information or other legal regulations
User can exercise the rights of paragraphs 1 to 3 through the procedures set by the Company.
Article 7 Company Contact
Company name and address are as follows
Trade name: UT LLC
Address: 15th floor, 343, Samil-daero, Jung-gu, Seoul
Phone number: 080-805-9622
Addendum
Article 1 Effective Date
These Terms are effective on April 1, 2021.
These Terms were amended on June 1, 2022.
These Terms were amended on August 8, 2022.
These Terms were amended on November 16, 2023.
These Terms were amended on February 23, 2024
Supplementary Terms for Korean Users: Transportation Platform Business Terms
Article 1 Purpose
The purpose of these Transportation Platform Business Terms (“these Terms”) is to set forth the rights, obligations and liabilities of User and UT LLC (“Company”), in connection with User’s usage of Platform Services provided by Company.
Article 2 Definitions
“Okivery App” means the mobile application or website provided by the Company to enable Franchisees, Non-Franchise Transportation Business Entities, and Users to use Company’s Platform Services.
“Franchisee” means a Passenger Transport Platform Business Entity under the Passenger Transport Service Act (“PTSA”) that has entered into a franchisee agreement with Company and provides Transportation Services to Users.
“Non-Franchise Transportation Business Entity" means a Transportation Business Entity, which provides Transportation Services to Users through the okivery App without entering into a franchise agreement with Company, and in these Terms, Franchisee and Non-Franchise Transportation Business Entity shall be collectively referred to as the “Transportation Business Entity”.
“Franchise Services” means the service provided by Company as a Passenger Platform Transport Franchise Entity under the PTSA, and includes the service of connecting Users to Franchisees by using the okivery App and any services incidental thereto.
“Brokerage Services” means the service provided by Company as a Passenger Platform Transport Brokerage Business Entity under the PTSA, and includes the service of connecting Users to Non-Franchise Transportation Business Entities by using the okivery App and any services incidental thereto.
“Platform Services” means Franchise Services and Brokerage Services together provided by Company.
. “Transportation Services” means Transportation Business Entity’s provision of transportation to User from departure point to destination, and “Transportation Fare” means the amount payable by User to Transportation Business Entity as consideration for Transportation Services.
“User” means a person who, by using the okivery App, uses Platform Services provided by Company and Transportation Services provided by Transportation Business Entity.
“Service Fee” means the amount payable by User to Company as consideration for Platform Services.
“Reserve Call” means the service by which a User may call a vehicle by reserving for a specific time as the User uses the Platform Services provided by the Company and the Transportation Services provided by a Transportation Business Entity, using the okivery App.
Article 3 Fare and Fee
1. As consideration for Transportation Services, User shall pay to Company, who collects such Transportation Fares from Users on behalf of Transportation Business Entities.
2. Transportation Fare shall be determined in principle by law, but Transportation Business Entities may charge Users the following Transportation Fares which have been reported and accepted by the competent authorities in accordance with the procedures set forth in the relevant laws.
A. When User uses Transportation Service through the okivery App, the estimated Transportation Fare shall be informed through the okivery App, and the Transportation Fare shall be charged in principle in accordance with the anticipated fares set forth in advance.
B. Notwithstanding section A, the final charge of Transportation Fare may be different from the expected rate set forth at the time of the call, in the event of circumstances unexpected by the Transportation Business Entity and/or the Company at the time Transportation Business Entity is called, such as the addition or change to User’s destination or via, or taking additional time than the expected time set forth at the time of the call.
3. Unless otherwise specified by applicable laws or the policies of Company and/or the Transportation Business Entity, Transportation Fare paid by User shall not be refunded.
4. When User use the Platform Services, the following terms apply:
A. Service Fees are calculated flexibly based on real-time demand and supply, and the Service Fees may be imposed on Users up to KRW 3,000.
B. In the case of a Reserve Call, a reservation fee, which is calculated flexibly based on real-time demand and supply, may be imposed up to KRW 50,000, considering the time of the reservation.
C. In the event User cancels the call after the assignment by the call confirmed, the cancellation fee may be imposed on User as set forth in the Appendix.
D. In the case of a Reserve Call, as the Transportation Business Entity must keep available the time for the User of the Reserve Call and not for other Users, a cancellation fee may be imposed as specified in the Appendix if the User of the Reserve Call cancels the call within one (1) hour from the planned time of boarding of the Reserve Call or does not board on the vehicle.
E. User can request a refund of Service Fees through okivery App, specifying the reason for the refund, and Company shall notify User of refund status within seven (7) business days.
Article 4 Liability and Compensation
1. Company shall be liable for damages incurred by Users in connection with their use of Platform Services, only to the extent such damages resulted from Company’s breach of these Terms or relevant laws. Except in case the damages are attributable to intentional wrongdoing or negligence of Company or otherwise set forth in relevant laws, Company shall not be liable for User’s use of Transportation Service.
2. If Company holds liability according to this article, the Company shall compensate for the damages resulting from Company’s intentional wronging or negligence, but as to damages going beyond the ordinary scope owing to special circumstances, the Company shall be responsible according to the Civil Code and other relevant laws.
Article 5 Indemnification
1. Notwithstanding Article 4 above, Company shall not be liable for any of the following; provided, that this shall not apply in the case of intentional wrongdoing or negligence of the Company, and, as to damages going beyond the ordinary scope owing to special circumstances, the Company shall be responsible according to the Civil Code and other relevant laws.
A. Damages resulting from causes beyond Company’s control, including, but not limited to, force majeure such as natural disasters, telecommunication interruption or willful misconduct or negligence by third parties;
B. Damages resulting from interruption of Platform Services;
C. Any loss of sales, profits or business opportunities experienced by User; or
D. Any and all legal liabilities resulting from User’s breach of law.
2. User agrees to indemnify and compensate the Company and its officers, directors, employees and agents for any and all claims for compensation or law suits by third parties (including attorney fees) arising out of or in connection with his/her breach of these Terms or relevant laws, or violation of the rights of any third party, including, but not limited to, Taxi Transportation Business Entities, their drivers, and other Users; provided, however, that in the event of a cause attributable to the Company, the scope of such indemnification and compensation shall be reduced according to the proportion attributable to Company.
Article 6 User’s Obligations
User shall comply with the following when using Platform Services or Transportation Services:
1. In no event shall User make any physical contact (including sexual misconduct or assault) or unwanted communication, engage in any behavior that may be considered threatening or rude, or demonstrate hatred towards a certain group against which discrimination is legally prohibited, to Transportation Business Entities and their drivers who provide Transportation Services or other Users.
2. No User under the age of 18 may use Platform Services, unless the User (a) is using the Transportation Services together with the legal guardian or (b) has obtained legal guardian’s consent.
3. In no event shall Users use Platform Services for freight delivery purposes, and use Transportation Services carrying any goods of which possession is prohibited under relevant laws, including, without limitation, illegal drug or weapon.
4. Users shall comply with the Road Traffic Act and other relevant laws, including, without limitation, wearing seat belts.
5. Users shall not violate relevant laws or terms of OKIVERY App, or violate the rights of any third party, including Transportation Business Entities, their drivers and other Users.
Article 7 Contact Information of the Company
The trade name and contact information of the Company are as follows:
1. Trade Name: OKIVERY
2. Address: 1F Sinjang-dong, Pyeongtaek
3. Phone: 070-000-0000
Article 8 Amendment to Terms
These Terms may be amended by the Company. Any amendment hereto shall be notified to Users no later than 7 days in advance upon relevant filings thereof are approved by the competent authority in accordance with relevant laws; provided, however, that for any amendments adverse or material to the User, the notification shall be made at least 30 days in advance both publicly and individually to each User.
Supplementary Provisions 
Article 1 Effective Date
These Terms shall become effective on March 1, 2024.
The previous Terms that have been in effect since November 23, 2023 shall be replaced by these Terms.
Appendix on Cancellation Fees
Cancellation Fees to be imposed on Users are as follows:
`;
